#before_script:
#  - docker info

stages:
  - build
  - deploy_nginx
  - deploy_php
  - clean_up

build:
  stage: build
  script:
    - docker-compose build
  tags:
    - docker-build

deploy_nginx:
  stage: deploy_nginx
  script:
    - docker tag dockercakephp_nginx $( echo $DOCKER_CLOUD_REPO_NGINX )
    - docker login --username=$DOCKER_CLOUD_USERNAME --email=$DOCKER_CLOUD_EMAIL --password=$DOCKER_CLOUD_PASSWORD
    - docker push $DOCKER_CLOUD_REPO_NGINX
  only:
    - master
    - dev
  when: on_success
  tags:
    - docker-build

deploy_php:
  stage: deploy_php
  script:
    - docker tag dockercakephp_php $( echo $DOCKER_CLOUD_REPO_PHP )
    - docker login --username=$DOCKER_CLOUD_USERNAME --email=$DOCKER_CLOUD_EMAIL --password=$DOCKER_CLOUD_PASSWORD
    - docker push $DOCKER_CLOUD_REPO_PHP
  only:
    - master
    - dev
  when: on_success
  tags:
    - docker-build

clean_up:
  stage: clean_up
  script:
    - docker rm $(docker ps -a -q) || true
    - docker rmi $(docker images | awk '/^<none>/ { print $3 }') || true
  tags:
    - docker-build
