before_script:
  - docker info

stages:
  - build
  - deploy_nginx
  - deploy_php-fpm
  - clean_up_nginx
  - clean_up_php-fpm

build:
  stage: build
  script:
    - docker-compose build
  tags:
    - docker-build

deploy_nginx:
  stage: deploy_nginx
  script:
    - docker tag dockercakephp_nginx:$( echo $CI_BUILD_REF_NAME ) $( echo $DOCKER_CLOUD_REPO_NGINX )
    - docker login --username=$DOCKER_CLOUD_USERNAME --email=$DOCKER_CLOUD_EMAIL --password=$DOCKER_CLOUD_PASSWORD
    - docker push $DOCKER_CLOUD_REPO_NGINX
  only:
    - master
    - dev
  when: on_success
  tags:
    - docker-build

deploy_php-fpm:
  stage: deploy_php-fpm
  script:
    - docker tag dockercakephp_php:$( echo $CI_BUILD_REF_NAME ) $( echo $DOCKER_CLOUD_REPO_PHP_FPM )
    - docker login --username=$DOCKER_CLOUD_USERNAME --email=$DOCKER_CLOUD_EMAIL --password=$DOCKER_CLOUD_PASSWORD
    - docker push $DOCKER_CLOUD_REPO_PHP_FPM
  only:
    - master
    - dev
  when: on_success
  tags:
    - docker-build

clean_up_nginx:
  stage: clean_up_nginx
  script:
    - docker rm $(docker ps -a | grep dockercakephp_nginx | awk '{print $1}') || true
    - docker rmi -f $(docker images | grep dockercakephp_nginx | awk '{print $3}') || true
  tags:
    - docker-build

clean_up_php-fpm:
  stage: clean_up_php-fpm
  script:
    - docker rm $(docker ps -a | grep dockercakephp_php | awk '{print $1}') || true
    - docker rmi -f $(docker images | dockercakephp_php | awk '{print $3}') || true
  tags:
    - docker-build
