stages:
  - build
  - deploy
  - sync

build:
  stage: build
  script:
    - docker build -t dockercakephp_php nginx
    - docker build -t dockercakephp_php php-fpm
  tags:
    - docker-build

deploy:
  stage: deploy
  script:
    - docker login --username=$DOCKER_CLOUD_USERNAME --email=$DOCKER_CLOUD_EMAIL --password=$DOCKER_CLOUD_PASSWORD
    - docker tag dockercakephp_nginx $( echo $DOCKER_CLOUD_REPO_NGINX )
    - docker tag dockercakephp_php $( echo $DOCKER_CLOUD_REPO_PHP )
    - docker push $DOCKER_CLOUD_REPO_NGINX
    - docker push $DOCKER_CLOUD_REPO_PHP
  only:
    - master
    - dev
  when: on_success
  tags:
    - docker-build

sync:
  stage: sync
  image: zaporylie/git
  script:
    - ssh-keyscan -H ${GIT_SYNC_REMOTE_HOST} >> ~/.ssh/known_hosts
    - git remote rm sync || true
    - git remote add sync ${GIT_SYNC_REMOTE_URL}
    - git checkout ${CI_BUILD_REF_NAME}
    - git pull origin ${CI_BUILD_REF_NAME}
    - git push sync ${CI_BUILD_REF_NAME}
  tags:
    - docker-build