before_script:
  - docker info

stages:
  - build
  - deploy_nginx
  - deploy_php
  - clean-up_nginx
  - clean-up_php

build:
  stage: build
  script:
    - docker-compose build
  tags:
    - docker-build

deploy_nginx:
  stage: deploy_nginx
  script:
    - docker tag dockercakephp_nginx $( echo $DOCKER_CLOUD_REPO_NGINX )
    - docker login --username=$DOCKER_CLOUD_USERNAME --email=$DOCKER_CLOUD_EMAIL --password=$DOCKER_CLOUD_PASSWORD
    - docker push $DOCKER_CLOUD_REPO_NGINX
  only:
    - master
    - dev
  when: on_success
  tags:
    - docker-build

deploy_php:
  stage: deploy_php
  script:
    - docker tag dockercakephp_php $( echo $DOCKER_CLOUD_REPO_PHP )
    - docker login --username=$DOCKER_CLOUD_USERNAME --email=$DOCKER_CLOUD_EMAIL --password=$DOCKER_CLOUD_PASSWORD
    - docker push $DOCKER_CLOUD_REPO_PHP
  only:
    - master
    - dev
  when: on_success
  tags:
    - docker-build

clean-up_nginx:
  stage: clean-up_nginx
  script:
    - docker rm $(docker ps -a | grep dockercakephp_nginx | awk '{print $1}') || true
    - docker rmi -f $(docker images | grep dockercakephp_nginx | awk '{print $3}') || true
  tags:
    - docker-build

clean-up_php:
  stage: clean-up_php
  script:
    - docker rm $(docker ps -a | grep dockercakephp_php | awk '{print $1}') || true
    - docker rmi -f $(docker images | dockercakephp_php | awk '{print $3}') || true
  tags:
    - docker-build
